In [1]:
import numpy as np

In [3]:
mat22 = np.array([[1,2],[3,4]])
mat22

array([[1, 2],
       [3, 4]])

In [4]:
mat22 + 1

array([[2, 3],
       [4, 5]])

In [5]:
np.cos(mat22)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [6]:
np.sum(mat22)

np.int64(10)

In [7]:
print(np.sum(mat22))

10


In [8]:
mat22bis = np.array([[5,6],[7,8]])
mat22 + mat22bis

array([[ 6,  8],
       [10, 12]])

In [10]:
mat23 = np.array(([[1,2,3],[4,5,6]]))
mat22 + mat23

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [13]:
v2 = np.array([1,2])
v2 + mat22

array([[2, 4],
       [4, 6]])

In [21]:
v12 = np.arange(12)
v12.shape

(12,)

In [22]:
m34 = v12.reshape(3,4)
m34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
m34.shape

(3, 4)

In [27]:
m43 = v12.reshape(4,-1)
m43

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
m43.shape

(4, 3)

In [28]:
cube232 = v12.reshape(-1,3,2)
cube232

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [29]:
v12 = cube232.reshape(-1)
v12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
m112 = v12.reshape(1,12)
m112

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [32]:
m121 = m112.T
m121

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [34]:
m34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
print(m34.sum())

66


In [36]:
m34.sum(axis=0)

array([12, 15, 18, 21])

In [38]:
m34.sum(axis=1)

array([ 6, 22, 38])

In [39]:
m34 * 2 + 1

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [40]:
def f(x):
    return 2 * x + 1

f(m34)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [41]:
f = lambda x: 2 * x + 1
f(m34)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [42]:
v4 = np.array([0,1,2,255], dtype=np.uint8)
v4

array([  0,   1,   2, 255], dtype=uint8)

In [43]:
v4 + 1

array([1, 2, 3, 0], dtype=uint8)

In [44]:
v4 - 1

array([255,   0,   1, 254], dtype=uint8)

In [46]:
result = v4 / 2
result.astype(np.uint8)

array([  0,   0,   1, 127], dtype=uint8)