In [2]:
import numpy as np

In [3]:
m23 = np.array([[1,2,3],[4,5,6]])
m23

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(np.sum(m23))

21


In [6]:
print(np.sum(m23, axis=0))

[5 7 9]


In [7]:
print(np.sum(m23, axis=1))

[ 6 15]


In [10]:
m23[:,1:]

array([[2, 3],
       [5, 6]])