In [1]:
# Loader le fichier
# Filtrer les données sur Absenteeism time in hours == 0 et les autres
# Moyenne et std du workload
# Rechercher tous les employés > 50 ans & workload > moyenne
# Dans les employés de plus de 50 ans & workload > moyenne prenez les 10 premiers (en position) et les 5 derniers (en position)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/absenteeism_at_work/Absenteeism_at_work.csv", delimiter=";")
df.describe()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
count,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,...,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000
mean,18.017568,19.216216,6.324324,3.914865,2.544595,221.329730,29.631081,12.554054,36.450000,271.490235,...,0.054054,1.291892,1.018919,0.567568,0.072973,0.745946,79.035135,172.114865,26.677027,6.924324
std,11.021247,8.433406,3.436287,1.421675,1.111831,66.952223,14.836788,4.384873,6.478772,39.058116,...,0.226277,0.673238,1.098489,0.495749,0.260268,1.318258,12.883211,6.034995,4.285452,13.330998
min,1.000000,0.000000,0.000000,2.000000,1.000000,118.000000,5.000000,1.000000,27.000000,205.917000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,56.000000,163.000000,19.000000,0.000000
25%,9.000000,13.000000,3.000000,3.000000,2.000000,179.000000,16.000000,9.000000,31.000000,244.387000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,69.000000,169.000000,24.000000,2.000000
50%,18.000000,23.000000,6.000000,4.000000,3.000000,225.000000,26.000000,13.000000,37.000000,264.249000,...,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,83.000000,170.000000,25.000000,3.000000
75%,28.000000,26.000000,9.000000,5.000000,4.000000,260.000000,50.000000,16.000000,40.000000,294.217000,...,0.000000,1.000000,2.000000,1.000000,0.000000,1.000000,89.000000,172.000000,31.000000,8.000000
max,36.000000,28.000000,12.000000,6.000000,4.000000,388.000000,52.000000,29.000000,58.000000,378.884000,...,1.000000,4.000000,4.000000,1.000000,1.000000,8.000000,108.000000,196.000000,38.000000,120.000000


In [4]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
df.columns

Index(['id', 'reason_for_absence', 'month_of_absence', 'day_of_the_week',
       'seasons', 'transportation_expense', 'distance_from_residence_to_work',
       'service_time', 'age', 'work_load_average/day', 'hit_target',
       'disciplinary_failure', 'education', 'son', 'social_drinker',
       'social_smoker', 'pet', 'weight', 'height', 'body_mass_index',
       'absenteeism_time_in_hours'],
      dtype='str')

In [5]:
df.dtypes

id                                   int64
reason_for_absence                   int64
month_of_absence                     int64
day_of_the_week                      int64
seasons                              int64
transportation_expense               int64
distance_from_residence_to_work      int64
service_time                         int64
age                                  int64
work_load_average/day              float64
hit_target                           int64
disciplinary_failure                 int64
education                            int64
son                                  int64
social_drinker                       int64
social_smoker                        int64
pet                                  int64
weight                               int64
height                               int64
body_mass_index                      int64
absenteeism_time_in_hours            int64
dtype: object

In [6]:
no_absent = df[df["absenteeism_time_in_hours"] == 0]
no_absent.head(10)

,id,reason_for_absence,month_of_absence,day_of_the_week,seasons,transportation_expense,distance_from_residence_to_work,service_time,age,work_load_average/day,...,disciplinary_failure,education,son,social_drinker,social_smoker,pet,weight,height,body_mass_index,absenteeism_time_in_hours
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,1,0,0,98,178,31,0
50,20,0,9,2,4,260,50,11,36,241.476,...,1,1,4,1,0,0,65,168,23,0
51,29,0,9,2,4,225,26,9,28,241.476,...,1,1,1,0,0,2,69,169,24,0
54,11,0,9,3,4,289,36,13,33,241.476,...,1,1,2,1,0,1,90,172,30,0
55,36,0,9,3,4,118,13,18,50,241.476,...,1,1,1,1,0,0,98,178,31,0
58,13,0,9,4,4,369,17,12,31,241.476,...,1,1,3,1,0,0,70,169,25,0
64,36,0,10,4,4,118,13,18,50,253.465,...,1,1,1,1,0,0,98,178,31,0
134,34,27,1,2,2,118,10,10,37,308.593,...,0,1,0,0,0,0,83,172,28,0
203,2,0,4,2,3,235,29,12,48,326.452,...,1,1,1,0,1,5,88,163,33,0
213,7,0,5,4,3,279,5,14,39,378.884,...,1,1,2,1,1,0,68,168,24,0


In [7]:
absent = df[df["absenteeism_time_in_hours"] != 0]
absent.head(10)

,id,reason_for_absence,month_of_absence,day_of_the_week,seasons,transportation_expense,distance_from_residence_to_work,service_time,age,work_load_average/day,...,disciplinary_failure,education,son,social_drinker,social_smoker,pet,weight,height,body_mass_index,absenteeism_time_in_hours
0,11,26,7,3,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,4
2,3,23,7,4,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,239.554,...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,239.554,...,0,1,2,1,0,1,90,172,30,2
5,3,23,7,6,1,179,51,18,38,239.554,...,0,1,0,1,0,0,89,170,31,2
6,10,22,7,6,1,361,52,3,28,239.554,...,0,1,1,1,0,4,80,172,27,8
7,20,23,7,6,1,260,50,11,36,239.554,...,0,1,4,1,0,0,65,168,23,4
8,14,19,7,2,1,155,12,14,34,239.554,...,0,1,2,1,0,0,95,196,25,40
9,1,22,7,2,1,235,11,14,37,239.554,...,0,3,1,0,0,1,88,172,29,8
10,20,1,7,2,1,260,50,11,36,239.554,...,0,1,4,1,0,0,65,168,23,8


In [8]:
absent_mean_workload = absent["work_load_average/day"].mean()
absent_std_workload = absent["work_load_average/day"].std()
absent_mean_workload, absent_std_workload

(np.float64(271.1657183908046), np.float64(39.09600315303554))

In [9]:
no_absent_mean_workload = no_absent["work_load_average/day"].mean()
no_absent_std_workload = no_absent["work_load_average/day"].std()
no_absent_mean_workload, no_absent_std_workload

(np.float64(276.6234999999999), np.float64(38.529052257792706))

In [10]:
df_sup50 = df[(df["age"] >= 50) & (df["work_load_average/day"] > absent_mean_workload)]
# df_sup50 = df[(df["age"] >= 50)][df["work_load_average/day"] > absent_mean_workload]
df_sup50

,id,reason_for_absence,month_of_absence,day_of_the_week,seasons,transportation_expense,distance_from_residence_to_work,service_time,age,work_load_average/day,...,disciplinary_failure,education,son,social_drinker,social_smoker,pet,weight,height,body_mass_index,absenteeism_time_in_hours
144,31,11,2,2,2,388,15,9,50,302.585,...,0,1,0,0,0,0,76,178,24,8
145,31,1,2,3,2,388,15,9,50,302.585,...,0,1,0,0,0,0,76,178,24,8
192,36,23,4,5,3,118,13,18,50,326.452,...,0,1,1,1,0,0,98,178,31,1
216,31,0,5,4,3,388,15,9,50,378.884,...,1,1,0,0,0,0,76,178,24,0
218,36,13,5,4,3,118,13,18,50,378.884,...,0,1,1,1,0,0,98,178,31,24
228,36,13,6,4,3,118,13,18,50,377.550,...,0,1,1,1,0,0,98,178,31,8
230,36,23,6,3,3,118,13,18,50,377.550,...,0,1,1,1,0,0,98,178,31,1
231,36,13,6,4,3,118,13,18,50,377.550,...,0,1,1,1,0,0,98,178,31,80
237,36,1,7,4,1,118,13,18,50,275.312,...,0,1,1,1,0,0,98,178,31,8
284,36,28,9,5,4,118,13,18,50,294.217,...,0,1,1,1,0,0,98,178,31,1


In [11]:
df_sup50.iloc[:10]

,id,reason_for_absence,month_of_absence,day_of_the_week,seasons,transportation_expense,distance_from_residence_to_work,service_time,age,work_load_average/day,...,disciplinary_failure,education,son,social_drinker,social_smoker,pet,weight,height,body_mass_index,absenteeism_time_in_hours
144,31,11,2,2,2,388,15,9,50,302.585,...,0,1,0,0,0,0,76,178,24,8
145,31,1,2,3,2,388,15,9,50,302.585,...,0,1,0,0,0,0,76,178,24,8
192,36,23,4,5,3,118,13,18,50,326.452,...,0,1,1,1,0,0,98,178,31,1
216,31,0,5,4,3,388,15,9,50,378.884,...,1,1,0,0,0,0,76,178,24,0
218,36,13,5,4,3,118,13,18,50,378.884,...,0,1,1,1,0,0,98,178,31,24
228,36,13,6,4,3,118,13,18,50,377.550,...,0,1,1,1,0,0,98,178,31,8
230,36,23,6,3,3,118,13,18,50,377.550,...,0,1,1,1,0,0,98,178,31,1
231,36,13,6,4,3,118,13,18,50,377.550,...,0,1,1,1,0,0,98,178,31,80
237,36,1,7,4,1,118,13,18,50,275.312,...,0,1,1,1,0,0,98,178,31,8
284,36,28,9,5,4,118,13,18,50,294.217,...,0,1,1,1,0,0,98,178,31,1


In [12]:
df_sup50.iloc[-5:]

,id,reason_for_absence,month_of_absence,day_of_the_week,seasons,transportation_expense,distance_from_residence_to_work,service_time,age,work_load_average/day,...,disciplinary_failure,education,son,social_drinker,social_smoker,pet,weight,height,body_mass_index,absenteeism_time_in_hours
366,36,26,1,2,2,118,13,18,50,330.061,...,0,1,1,1,0,0,98,178,31,4
521,9,1,10,4,4,228,14,16,58,284.853,...,0,1,2,0,0,1,65,172,22,1
711,36,19,6,5,3,118,13,18,50,275.089,...,0,1,1,1,0,0,98,178,31,24
716,36,19,6,5,3,118,13,18,50,275.089,...,0,1,1,1,0,0,98,178,31,3
739,35,0,0,6,3,179,45,14,53,271.219,...,0,1,1,0,0,1,77,175,25,0


In [13]:
# Créer une colonne absence_category
# Pour 0h, 4h, 8, 24, au delà (max)
# Faire un iterrows et n'afficher que les absence_category == 0

In [14]:
absent_max = df["absenteeism_time_in_hours"].max()
absent_max

np.int64(120)

In [15]:
bins = [-1, 0, 4, 8, 24, absent_max]
labels = ['Aucune', 'Courte (1-4h)', 'Demi-journée (5-8h)', 'Longue (9-24h)', 'Très longue (>24h)']
category = pd.cut(df["absenteeism_time_in_hours"], bins=bins, labels=False)
df["absence_category"] = category
# df["absence_category_label"]  = pd.cut(df["absenteeism_time_in_hours"], bins=bins, labels=labels)
df["absence_category"] = df["absence_category"].astype(np.int32)
# df["absence_category_label"] = df["absence_category_label"].astype(np.int32)
df.head(10)


,id,reason_for_absence,month_of_absence,day_of_the_week,seasons,transportation_expense,distance_from_residence_to_work,service_time,age,work_load_average/day,...,education,son,social_drinker,social_smoker,pet,weight,height,body_mass_index,absenteeism_time_in_hours,absence_category
0,11,26,7,3,1,289,36,13,33,239.554,...,1,2,1,0,1,90,172,30,4,1
1,36,0,7,3,1,118,13,18,50,239.554,...,1,1,1,0,0,98,178,31,0,0
2,3,23,7,4,1,179,51,18,38,239.554,...,1,0,1,0,0,89,170,31,2,1
3,7,7,7,5,1,279,5,14,39,239.554,...,1,2,1,1,0,68,168,24,4,1
4,11,23,7,5,1,289,36,13,33,239.554,...,1,2,1,0,1,90,172,30,2,1
5,3,23,7,6,1,179,51,18,38,239.554,...,1,0,1,0,0,89,170,31,2,1
6,10,22,7,6,1,361,52,3,28,239.554,...,1,1,1,0,4,80,172,27,8,2
7,20,23,7,6,1,260,50,11,36,239.554,...,1,4,1,0,0,65,168,23,4,1
8,14,19,7,2,1,155,12,14,34,239.554,...,1,2,1,0,0,95,196,25,40,4
9,1,22,7,2,1,235,11,14,37,239.554,...,3,1,0,0,1,88,172,29,8,2


In [16]:
df.groupby('absence_category').mean()["pet"]

absence_category
0    1.022727
1    0.640288
2    0.995370
3    0.285714
4    0.535714
Name: pet, dtype: float64

In [17]:
for index, row in df.iterrows():
    if row["absence_category"] == 0:
        print(row.values)

[ 36.      0.      7.      3.      1.    118.     13.     18.     50.
 239.554  97.      1.      1.      1.      1.      0.      0.     98.
 178.     31.      0.      0.   ]
[ 20.      0.      9.      2.      4.    260.     50.     11.     36.
 241.476  92.      1.      1.      4.      1.      0.      0.     65.
 168.     23.      0.      0.   ]
[ 29.      0.      9.      2.      4.    225.     26.      9.     28.
 241.476  92.      1.      1.      1.      0.      0.      2.     69.
 169.     24.      0.      0.   ]
[ 11.      0.      9.      3.      4.    289.     36.     13.     33.
 241.476  92.      1.      1.      2.      1.      0.      1.     90.
 172.     30.      0.      0.   ]
[ 36.      0.      9.      3.      4.    118.     13.     18.     50.
 241.476  92.      1.      1.      1.      1.      0.      0.     98.
 178.     31.      0.      0.   ]
[ 13.      0.      9.      4.      4.    369.     17.     12.     31.
 241.476  92.      1.      1.      3.      1.      0.      0

In [18]:
[row.values for index, row in df.iterrows() if row["absence_category"] == 0]

[array([ 36.   ,   0.   ,   7.   ,   3.   ,   1.   , 118.   ,  13.   ,
         18.   ,  50.   , 239.554,  97.   ,   1.   ,   1.   ,   1.   ,
          1.   ,   0.   ,   0.   ,  98.   , 178.   ,  31.   ,   0.   ,
          0.   ]),
 array([ 20.   ,   0.   ,   9.   ,   2.   ,   4.   , 260.   ,  50.   ,
         11.   ,  36.   , 241.476,  92.   ,   1.   ,   1.   ,   4.   ,
          1.   ,   0.   ,   0.   ,  65.   , 168.   ,  23.   ,   0.   ,
          0.   ]),
 array([ 29.   ,   0.   ,   9.   ,   2.   ,   4.   , 225.   ,  26.   ,
          9.   ,  28.   , 241.476,  92.   ,   1.   ,   1.   ,   1.   ,
          0.   ,   0.   ,   2.   ,  69.   , 169.   ,  24.   ,   0.   ,
          0.   ]),
 array([ 11.   ,   0.   ,   9.   ,   3.   ,   4.   , 289.   ,  36.   ,
         13.   ,  33.   , 241.476,  92.   ,   1.   ,   1.   ,   2.   ,
          1.   ,   0.   ,   1.   ,  90.   , 172.   ,  30.   ,   0.   ,
          0.   ]),
 array([ 36.   ,   0.   ,   9.   ,   3.   ,   4.   , 118.   ,  13.   ,
 

In [19]:
df.groupby("absenteeism_time_in_hours").size()

absenteeism_time_in_hours
0       44
1       88
2      157
3      112
4       60
5        7
7        1
8      208
16      19
24      16
32       6
40       7
48       1
56       2
64       3
80       3
104      1
112      2
120      3
dtype: int64

In [20]:
df.groupby("absence_category").size()

absence_category
0     44
1    417
2    216
3     35
4     28
dtype: int64