In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv("data/heartdisease/data_with_nan.csv", na_values=".")
# df.dtypes
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130.0,132.0,0.0,2.0,185.0,0.0,0.0,NaN,NaN,NaN,0
1,29,1,2,120.0,243.0,0.0,0.0,160.0,0.0,0.0,NaN,NaN,NaN,0
2,29,1,2,140.0,NaN,0.0,0.0,170.0,0.0,0.0,NaN,NaN,NaN,0
3,30,0,1,170.0,237.0,0.0,1.0,170.0,0.0,0.0,NaN,NaN,6.0,0
4,31,0,2,100.0,219.0,0.0,1.0,150.0,0.0,0.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.0,0.0,0.0,94.0,1.0,2.5,NaN,NaN,NaN,1
290,54,0,3,130.0,294.0,0.0,1.0,100.0,1.0,0.0,2.0,NaN,NaN,1
291,56,1,4,155.0,342.0,1.0,0.0,150.0,1.0,3.0,2.0,NaN,NaN,1
292,58,0,2,180.0,393.0,0.0,0.0,110.0,1.0,1.0,2.0,NaN,7.0,1


In [3]:
df.isnull().sum()

age           0
sex           0
cp            0
trestbps      1
chol         23
fbs           8
restecg       1
thalach       1
exang         1
oldpeak       0
slope       190
ca          291
thal        266
num           0
dtype: int64

In [4]:
# Pour slope, ca & thal droper les colonnes
# Pour chol créer une fonction qui créer mean + std * (rnd - 0.5) * 2 et l'appliquer avec la fonction apply
# .apply(lambda c: chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c)
# Pour trestbps, restecg, thalach & exang & fbs droper les lignes avec dropna

In [5]:
df = df.drop(["slope", "ca", "thal"], axis=1)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.0,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.0,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,NaN,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.0,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.0,0.0,1.0,150.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.0,0.0,0.0,94.0,1.0,2.5,1
290,54,0,3,130.0,294.0,0.0,1.0,100.0,1.0,0.0,1
291,56,1,4,155.0,342.0,1.0,0.0,150.0,1.0,3.0,1
292,58,0,2,180.0,393.0,0.0,0.0,110.0,1.0,1.0,1


In [6]:
def chol_replace(c):
    chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c

In [7]:
chol_mean = df["chol"].mean()
chol_std = df["chol"].std()
df["chol"] = df["chol"].apply(lambda c: chol_mean + chol_std * (np.random.rand() - 0.5) * 2 if pd.isnull(c) else c)
# df["chol"] = df["chol"].apply(chol_replace)
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.000000,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.000000,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,213.736987,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.000000,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.000000,0.0,1.0,150.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.000000,0.0,0.0,94.0,1.0,2.5,1
290,54,0,3,130.0,294.000000,0.0,1.0,100.0,1.0,0.0,1
291,56,1,4,155.0,342.000000,1.0,0.0,150.0,1.0,3.0,1
292,58,0,2,180.0,393.000000,0.0,0.0,110.0,1.0,1.0,1


In [8]:
df = df.dropna()
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.000000,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.000000,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,213.736987,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.000000,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.000000,0.0,1.0,150.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160.0,331.000000,0.0,0.0,94.0,1.0,2.5,1
290,54,0,3,130.0,294.000000,0.0,1.0,100.0,1.0,0.0,1
291,56,1,4,155.0,342.000000,1.0,0.0,150.0,1.0,3.0,1
292,58,0,2,180.0,393.000000,0.0,0.0,110.0,1.0,1.0,1


In [9]:
df.to_csv("data/heartdisease/dataclean.csv", index=None)

In [12]:
for row in df.values:
    # for col in row:
    #     print(col)
    print(row)

[ 28.   1.   2. 130. 132.   0.   2. 185.   0.   0.   0.]
[ 29.   1.   2. 120. 243.   0.   0. 160.   0.   0.   0.]
[ 29.           1.           2.         140.         213.73698701
   0.           0.         170.           0.           0.
   0.        ]
[ 30.   0.   1. 170. 237.   0.   1. 170.   0.   0.   0.]
[ 31.   0.   2. 100. 219.   0.   1. 150.   0.   0.   0.]
[ 32.   0.   2. 105. 198.   0.   0. 165.   0.   0.   0.]
[ 32.   1.   2. 110. 225.   0.   0. 184.   0.   0.   0.]
[ 32.   1.   2. 125. 254.   0.   0. 155.   0.   0.   0.]
[ 33.   1.   3. 120. 298.   0.   0. 185.   0.   0.   0.]
[ 34.   0.   2. 130. 161.   0.   0. 190.   0.   0.   0.]
[ 34.   1.   2. 150. 214.   0.   1. 168.   0.   0.   0.]
[ 34.   1.   2.  98. 220.   0.   0. 150.   0.   0.   0.]
[ 35.   0.   1. 120. 160.   0.   1. 185.   0.   0.   0.]
[ 35.   0.   4. 140. 167.   0.   0. 150.   0.   0.   0.]
[ 35.   1.   2. 120. 308.   0.   2. 180.   0.   0.   0.]
[ 35.   1.   2. 150. 264.   0.   0. 168.   0.   0.   0.]
[ 36. 

In [15]:
for index, row in df.iterrows():
    for col in row:
        print(col)

28.0
1.0
2.0
130.0
132.0
0.0
2.0
185.0
0.0
0.0
0.0
29.0
1.0
2.0
120.0
243.0
0.0
0.0
160.0
0.0
0.0
0.0
29.0
1.0
2.0
140.0
213.73698701383432
0.0
0.0
170.0
0.0
0.0
0.0
30.0
0.0
1.0
170.0
237.0
0.0
1.0
170.0
0.0
0.0
0.0
31.0
0.0
2.0
100.0
219.0
0.0
1.0
150.0
0.0
0.0
0.0
32.0
0.0
2.0
105.0
198.0
0.0
0.0
165.0
0.0
0.0
0.0
32.0
1.0
2.0
110.0
225.0
0.0
0.0
184.0
0.0
0.0
0.0
32.0
1.0
2.0
125.0
254.0
0.0
0.0
155.0
0.0
0.0
0.0
33.0
1.0
3.0
120.0
298.0
0.0
0.0
185.0
0.0
0.0
0.0
34.0
0.0
2.0
130.0
161.0
0.0
0.0
190.0
0.0
0.0
0.0
34.0
1.0
2.0
150.0
214.0
0.0
1.0
168.0
0.0
0.0
0.0
34.0
1.0
2.0
98.0
220.0
0.0
0.0
150.0
0.0
0.0
0.0
35.0
0.0
1.0
120.0
160.0
0.0
1.0
185.0
0.0
0.0
0.0
35.0
0.0
4.0
140.0
167.0
0.0
0.0
150.0
0.0
0.0
0.0
35.0
1.0
2.0
120.0
308.0
0.0
2.0
180.0
0.0
0.0
0.0
35.0
1.0
2.0
150.0
264.0
0.0
0.0
168.0
0.0
0.0
0.0
36.0
1.0
2.0
120.0
166.0
0.0
0.0
180.0
0.0
0.0
0.0
36.0
1.0
3.0
112.0
340.0
0.0
0.0
184.0
0.0
1.0
0.0
36.0
1.0
3.0
130.0
209.0
0.0
0.0
178.0
0.0
0.0
0.0
36.0
1.0
3.0
150.0
